name: pa32
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.7

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
    


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  fluro: ^2.0.3
  flutter_swiper_null_safety: ^1.0.2
  google_maps_flutter: ^2.1.3
  fluttertoast: ^8.0.9
  scan: ^1.6.0
  date_format: ^2.0.5
  flutter_cupertino_date_picker: ^1.0.26+2
  geocoding: ^2.0.4
  geolocator: ^8.2.0
  crypto: ^3.0.1
  dio: ^4.0.6
  flutter_easyloading: ^3.0.3
  shared_preferences: ^2.0.13
  image_picker: ^0.8.4+10
  http_parser: ^4.0.0
  custom_info_window: ^1.0.1
  flutter_pickers: ^2.1.8
  flutter_screenutil: 5.3.1
  package_info_plus: ^1.4.2
  flutter_blue: ^0.8.0
  flutter_sms: ^2.3.3
  flutter_phone_direct_caller: ^2.1.1
  expandable: ^5.0.1
  auto_size_text: ^3.0.0
  vibration: ^1.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/main_marker.png
   - assets/images/avatar.png
   - assets/images/alarm.png
   - assets/images/about.png
   - assets/images/about_x2.png
   - assets/images/me_alert.png
   - assets/images/call.png
   - assets/images/call_dafult.png
   - assets/images/cares_add.png
   - assets/images/cares_return.png
   - assets/images/cares_next.png
   - assets/images/dial.png
   - assets/images/dial_dafult.png
   - assets/images/earth.png
   - assets/images/focus.png
   - assets/images/fold.png
   - assets/images/drawer.png
   - assets/images/map.png
   - assets/images/me_alert.png
   - assets/images/me_alert_x2.png
   - assets/images/user.png
   - assets/images/password.png
   - assets/images/password2.png
   - assets/images/logout.png
   - assets/images/me_cares.png
   - assets/images/me_sos.png
   - assets/images/pa32.png
   - assets/images/delete.png
   - assets/images/add.png
   - assets/images/next.png
   - assets/images/duration.png
   - assets/images/position.png
   - assets/images/positionMax.png
   - assets/images/mapBg.png
   - assets/images/PowerOff.png
   - assets/images/Overspeed.png
   - assets/images/removeDevice.png
   - assets/images/highTemperature.png
   - assets/images/LowTemperature.png
   - assets/images/powerOutage.png
   - assets/images/ExitFence.png
   - assets/images/BatteryLow.png
   - assets/images/SOS.png
   - assets/images/MotionStart.png
   - assets/images/MotionStop.png
   - assets/images/OnCharge.png
   - assets/images/OffCharge.png
   - assets/images/PowerOn.png
   - assets/images/IgnitionOn.png
   - assets/images/IgnitionOff.png
   - assets/images/HighHumidity.png
   - assets/images/LowHumidity.png
   - assets/images/battery_high.png
   - assets/images/battery_eighty.png
   - assets/images/battery_center.png
   - assets/images/battery_forty.png
   - assets/images/battery_low.png
   - assets/images/battery_no.png
   - assets/images/verification.png
   - assets/images/service_add.png
   - assets/images/service_return.png
   - assets/images/address_search.png
   - assets/images/about_icon.png
   - assets/images/contact_us.png
   - assets/images/scan_icon.png
   - assets/images/default_earth.png
   - assets/images/check_earth.png
   - assets/images/down_arr.png
   - assets/images/this_location.png
   - assets/images/location.png
   - assets/images/app logo final.png


       # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
